stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - ./scripts/build.sh

test-job:
  stage: test
  script:
    - ./scripts/test.sh

deploy-job:
  stage: deploy
  script:
    - ./scripts/deploy.sh
  only:
    - main
